// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBUVhnH-dTMy1MJDnZyN6x0gmNbpKSNsg',
    appId: '1:367655408121:web:3aa631c63edbbdb3496d28',
    messagingSenderId: '367655408121',
    projectId: 'tourmate-70d03',
    authDomain: 'tourmate-70d03.firebaseapp.com',
    storageBucket: 'tourmate-70d03.firebasestorage.app',
    measurementId: 'G-ES8RQSM9ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC94cFIsMetstkuliajCEqh-E6KamrbE1k',
    appId: '1:367655408121:android:cd0d7846e3f81d3e496d28',
    messagingSenderId: '367655408121',
    projectId: 'tourmate-70d03',
    storageBucket: 'tourmate-70d03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_7_B0nJYwWhKT4HHmGqmcn3qZ1scZGuk',
    appId: '1:367655408121:ios:ece0e7e798d9a977496d28',
    messagingSenderId: '367655408121',
    projectId: 'tourmate-70d03',
    storageBucket: 'tourmate-70d03.firebasestorage.app',
    iosBundleId: 'com.example.tourmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_7_B0nJYwWhKT4HHmGqmcn3qZ1scZGuk',
    appId: '1:367655408121:ios:ece0e7e798d9a977496d28',
    messagingSenderId: '367655408121',
    projectId: 'tourmate-70d03',
    storageBucket: 'tourmate-70d03.firebasestorage.app',
    iosBundleId: 'com.example.tourmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBUVhnH-dTMy1MJDnZyN6x0gmNbpKSNsg',
    appId: '1:367655408121:web:7ae287a491db614b496d28',
    messagingSenderId: '367655408121',
    projectId: 'tourmate-70d03',
    authDomain: 'tourmate-70d03.firebaseapp.com',
    storageBucket: 'tourmate-70d03.firebasestorage.app',
    measurementId: 'G-QS21DZGH2D',
  );
}
